blueprint:
  name: deCONZ - Namron 1, 2 and 4 kanal bryter
  description: |
    Controll lights and other with Namron zigbee remote

  domain: automation
  input:
    remote:
      name: Remote
      description: Namron controller
      selector:
        device:
          integration: deconz
          manufacturer: Namron AS

    button1:
      name: Button 1 short press
      default: []
      selector:
        action: {}
    button2:
      name: Button 2 short press
      default: []
      selector:
        action: {}
    button3:
      name: Button 3 short press
      default: []
      selector:
        action: {}
    button4:
      name: Button 4 short press
      default: []
      selector:
        action: {}
    button5:
      name: Button 5 short press
      default: []
      selector:
        action: {}
    button6:
      name: Button 6 short press
      default: []
      selector:
        action: {}
    button7:
      name: Button 7 short press
      default: []
      selector:
        action: {}
    button8:
      name: Button 8 short press
      default: []
      selector:
        action: {}

        
mode: restart
max_exceeded: silent


trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input 'remote'

action:
  - variables:
      event: '{{ trigger.event.data.event }}'
      
  - choose:
      - conditions:
          - '{{ event == 1002 }}'
        sequence: !input 'button1'
      - conditions:
          - '{{ event == 2002 }}'
        sequence: !input 'button2'
      - conditions:
          - '{{ event == 3002 }}'
        sequence: !input 'button3'
      - conditions:
          - '{{ event == 4002 }}'
        sequence: !input 'button4'
      - conditions:
          - '{{ event == 5002 }}'
        sequence: !input 'button5'
      - conditions:
          - '{{ event == 6002 }}'
        sequence: !input 'button6'
      - conditions:
          - '{{ event == 7002 }}'
        sequence: !input 'button7'
      - conditions:
          - '{{ event == 8002 }}'
        sequence: !input 'button8'


    