blueprint:
  name: Zigbee2MQTT - Aqara WXKG11LM (aq2) - Single Button
  description: >
    Blueprint for Aqara WXKG11LM (aq2) single-button switch using Zigbee2MQTT.
    It listens to the `sensor.<friendly_name>_action` entity and maps
    actions such as single, double, triple, quadruple, many, hold, and release
    to custom automations.

    🛈 Notes:
    - The device must expose the `action` entity in Zigbee2MQTT.
    - In Home Assistant, this usually appears as `sensor.<friendly_name>_action`.
    - If the entity is missing, check that your device is updated and exposes
      `action` under "Exposes" in Zigbee2MQTT.
  domain: automation
  source_url: https://github.com/ingebrethsenrm/Home-Assistant
  input:
    action_entity:
      name: Action Sensor (Z2M)
      description: Select the entity called something like sensor.<friendly_name>_action
      selector:
        entity:
          domain: sensor

    # Actions
    single_action:
      name: Single Press
      description: Triggered when the button is pressed once
      default: []
      selector:
        action: {}
    double_action:
      name: Double Press
      description: Triggered when the button is pressed twice
      default: []
      selector:
        action: {}
    triple_action:
      name: Triple Press
      description: Triggered when the button is pressed three times
      default: []
      selector:
        action: {}
    quadruple_action:
      name: Quadruple Press
      description: Triggered when the button is pressed four times
      default: []
      selector:
        action: {}
    many_action:
      name: Many Presses (5+)
      description: Triggered when the button is pressed multiple times rapidly
      default: []
      selector:
        action: {}
    hold_action:
      name: Hold
      description: Triggered when the button is held down
      default: []
      selector:
        action: {}
    release_action:
      name: Release
      description: Triggered when the button is released after being held
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

variables:
  action_entity: !input action_entity

trigger:
  - platform: state
    entity_id: !input action_entity

action:
  - variables:
      z2m_action: "{{ trigger.to_state.state | lower }}"
  - choose:
      - conditions: "{{ z2m_action == 'single' }}"
        sequence: !input single_action
      - conditions: "{{ z2m_action == 'double' }}"
        sequence: !input double_action
      - conditions: "{{ z2m_action == 'triple' }}"
        sequence: !input triple_action
      - conditions: "{{ z2m_action == 'quadruple' }}"
        sequence: !input quadruple_action
      - conditions: "{{ z2m_action == 'many' }}"
        sequence: !input many_action
      - conditions: "{{ z2m_action == 'hold' }}"
        sequence: !input hold_action
      - conditions: "{{ z2m_action == 'release' }}"
        sequence: !input release_action
    default: []
