blueprint:
  name: deCONZ - Namron - 4512721 - 4 channel switch
  description: 'Controll lights and other with Namron zigbee remote 4512721, 4 channels, 8 buttons.'
  domain: automation
  input:
    remote:
      name: Remote
      description: Namron controller
      selector:
        device:
          integration: deconz
          manufacturer: Namron AS
          model: lumi.remote.b686opcn01

    # ---------------------------- ROW 1 LEFT ----------------------------
    button_row1_left_single_press:
      name: Row 1 left button - Single press
      description: Action to run on a single press of left button, row 1
      default: []
      selector:
        action: {}

    button_row1_left_hold_in:
      name: Row 1 left button - Hold
      description: Action to run when row 1, left button is held in
      default: []
      selector:
        action: {}

    button_row1_left_hold_release:
      name: Row 1 left button - Hold release
      description: Action to run when row 1, left button was held in and released
      default: []
      selector:
        action: {}

    # ---------------------------- ROW 1 RIGHT ----------------------------
    button_row1_right_single_press:
      name: Row 1 right button - Single press
      description: Action to run on a single press of right button, row 1
      default: []
      selector:
        action: {}

    button_row1_right_hold_in:
      name: Row 1 right button - Hold
      description: Action to run when row 1, right button is held in
      default: []
      selector:
        action: {}

    button_row1_right_hold_release:
      name: Row 1 right button - Hold release
      description: Action to run when row 1, right button was held in and released
      default: []
      selector:
        action: {}

    # ---------------------------- ROW 2 LEFT ----------------------------
    button_row2_left_single_press:
      name: Row 2 left button - Single press
      description: Action to run on a single press of left button, row 2
      default: []
      selector:
        action: {}

    button_row2_left_hold_in:
      name: Row 2 left button - Hold
      description: Action to run when row 2, left button is held in
      default: []
      selector:
        action: {}

    button_row2_left_hold_release:
      name: Row 2 left button - Hold release
      description: Action to run when row 2, left button was held in and released
      default: []
      selector:
        action: {}

    # ---------------------------- ROW 2 RIGHT ----------------------------
    button_row2_right_single_press:
      name: Row 2 right button - Single press
      description: Action to run on a single press of right button, row 2
      default: []
      selector:
        action: {}

    button_row2_right_hold_in:
      name: Row 2 right button - Hold
      description: Action to run when row 2, right button is held in
      default: []
      selector:
        action: {}

    button_row2_right_hold_release:
      name: Row 2 right button - Hold release
      description: Action to run when row 2, right button was held in and released
      default: []
      selector:
        action: {}

    # ---------------------------- ROW 3 LEFT ----------------------------
    button_row3_left_single_press:
      name: Row 3 left button - Single press
      description: Action to run on a single press of left button, row 3
      default: []
      selector:
        action: {}

    button_row3_left_hold_in:
      name: Row 3 left button - Hold
      description: Action to run when row 3, left button is held in
      default: []
      selector:
        action: {}

    button_row3_left_hold_release:
      name: Row 3 left button - Hold release
      description: Action to run when row 3, left button was held in and released
      default: []
      selector:
        action: {}

    # ---------------------------- ROW 3 RIGHT ----------------------------
    button_row3_right_single_press:
      name: Row 3 right button - Single press
      description: Action to run on a single press of right button, row 3
      default: []
      selector:
        action: {}

    button_row3_right_hold_in:
      name: Row 3 right button - Hold
      description: Action to run when row 3, right button is held in
      default: []
      selector:
        action: {}

    button_row3_right_hold_release:
      name: Row 3 right button - Hold release
      description: Action to run when row 3, right button was held in and released
      default: []
      selector:
        action: {}

    # ---------------------------- ROW 4 LEFT ----------------------------
    button_row4_left_single_press:
      name: Row 4 left button - Single press
      description: Action to run on a single press of left button, row 4
      default: []
      selector:
        action: {}

    button_row4_left_hold_in:
      name: Row 4 left button - Hold
      description: Action to run when row 4, left button is held in
      default: []
      selector:
        action: {}

    button_row4_left_hold_release:
      name: Row 4 left button - Hold release
      description: Action to run when row 4, left button was held in and released
      default: []
      selector:
        action: {}

    # ---------------------------- ROW 4 RIGHT ----------------------------
    button_row4_right_single_press:
      name: Row 4 right button - Single press
      description: Action to run on a single press of right button, row 4
      default: []
      selector:
        action: {}

    button_row4_right_hold_in:
      name: Row 4 right button - Hold
      description: Action to run when row 4, right button is held in
      default: []
      selector:
        action: {}

    button_row4_right_hold_release:
      name: Row 4 right button - Hold release
      description: Action to run when row 4, right button was held in and released
      default: []
      selector:
        action: {}


        
mode: restart
max_exceeded: silent


trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input 'remote'

action:
  - variables:
      event: '{{ trigger.event.data.event }}'
      
  - choose:
      # ---------------------------- ROW 1 LEFT ----------------------------
      - conditions:
        - '{{ event == 1002 }}'
        sequence: !input 'button_row1_left_single_press'
      - conditions:
        - '{{ event == 1001 }}'
        sequence: !input 'button_row1_left_hold_in'
      - conditions:
        - '{{ event == 1003 }}'
        sequence: !input 'button_row1_left_hold_release'

      # ---------------------------- ROW 1 RIGHT ----------------------------
      - conditions:
        - '{{ event == 2002 }}'
        sequence: !input 'button_row1_right_single_press'
      - conditions:
        - '{{ event == 2001 }}'
        sequence: !input 'button_row1_right_hold_in'
      - conditions:
        - '{{ event == 2003 }}'
        sequence: !input 'button_row1_right_hold_release'

      # ---------------------------- ROW 2 LEFT ----------------------------
      - conditions:
        - '{{ event == 3002 }}'
        sequence: !input 'button_row2_left_single_press'
      - conditions:
        - '{{ event == 3001 }}'
        sequence: !input 'button_row2_left_hold_in'
      - conditions:
        - '{{ event == 3003 }}'
        sequence: !input 'button_row2_left_hold_release'

      # ---------------------------- ROW 2 RIGHT ----------------------------
      - conditions:
        - '{{ event == 4002 }}'
        sequence: !input 'button_row2_right_single_press'
      - conditions:
        - '{{ event == 4001 }}'
        sequence: !input 'button_row2_right_hold_in'
      - conditions:
        - '{{ event == 4003 }}'
        sequence: !input 'button_row2_right_hold_release'

      # ---------------------------- ROW 3 LEFT ----------------------------
      - conditions:
        - '{{ event == 5002 }}'
        sequence: !input 'button_row3_left_single_press'
      - conditions:
        - '{{ event == 5001 }}'
        sequence: !input 'button_row3_left_hold_in'
      - conditions:
        - '{{ event == 5003 }}'
        sequence: !input 'button_row3_left_hold_release'

      # ---------------------------- ROW 3 RIGHT ----------------------------
      - conditions:
        - '{{ event == 6002 }}'
        sequence: !input 'button_row3_right_single_press'
      - conditions:
        - '{{ event == 6001 }}'
        sequence: !input 'button_row3_right_hold_in'
      - conditions:
        - '{{ event == 6003 }}'
        sequence: !input 'button_row3_right_hold_release'

      # ---------------------------- ROW 4 LEFT ----------------------------
      - conditions:
        - '{{ event == 7002 }}'
        sequence: !input 'button_row4_left_single_press'
      - conditions:
        - '{{ event == 7001 }}'
        sequence: !input 'button_row4_left_hold_in'
      - conditions:
        - '{{ event == 7003 }}'
        sequence: !input 'button_row4_left_hold_release'

      # ---------------------------- ROW 4 RIGHT ----------------------------
      - conditions:
        - '{{ event == 8002 }}'
        sequence: !input 'button_row4_right_single_press'
      - conditions:
        - '{{ event == 8001 }}'
        sequence: !input 'button_row4_right_hold_in'
      - conditions:
        - '{{ event == 8003 }}'
        sequence: !input 'button_row4_right_hold_release'


    